name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write  # 允许工作流创建 releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version
        id: get_version
        shell: bash  # ✅ 显式指定 bash 否则 sh 默认不支持 [[ ]]
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=dev-$(date +%Y%m%d)" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: |
          rm -rf release
          mkdir -p release

          # 设置正确的模块路径
          go mod tidy

          for GOARCH in amd64 386 arm arm64; do
            OUTPUT="traffic-monitor-$GOARCH"
            GOOS=linux GOARCH=$GOARCH go build -v -o release/$OUTPUT .
            cp release/$OUTPUT release/traffic-monitor
            cd release && tar -czvf "traffic-monitor-$GOARCH-${VERSION}.tar.gz" traffic-monitor && rm traffic-monitor && cd ..
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: release/*.tar.gz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

