name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write  # 允许工作流创建 releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=dev-$(date +%Y%m%d)" >> $GITHUB_ENV
          fi

      - name: Build binaries
        run: |
          rm -rf release
          mkdir -p release
          
          # 设置正确的模块路径
          go mod tidy
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -v -o release/traffic-monitor-amd64 .
          cd release && tar -czvf "traffic-monitor-amd64-$VERSION.tar.gz" traffic-monitor-amd64 && cd ..
          
          # Linux 386
          GOOS=linux GOARCH=386 go build -v -o release/traffic-monitor-386 .
          cd release && tar -czvf "traffic-monitor-386-$VERSION.tar.gz" traffic-monitor-386 && cd ..
          
          # Linux ARM
          GOOS=linux GOARCH=arm go build -v -o release/traffic-monitor-arm .
          cd release && tar -czvf "traffic-monitor-arm-$VERSION.tar.gz" traffic-monitor-arm && cd ..
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -v -o release/traffic-monitor-arm64 .
          cd release && tar -czvf "traffic-monitor-arm64-$VERSION.tar.gz" traffic-monitor-arm64 && cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: release/*.tar.gz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
