name: Build and Package Go Binary

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  pull_request:
    branches:
      - main  # 当有拉取请求合并到主分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取代码

    - name: Set up Go
      uses: actions/setup-go@v3  # 设置 Go 环境
      with:
        go-version: '1.20'  # 使用 Go 1.20 或根据需要修改版本

    - name: Install dependencies
      run: go mod tidy  # 安装 Go 依赖项

    - name: Build Go project
      run: |
        go build -o traffic-monitor  # 编译 Go 项目并生成二进制文件 traffic-monitor

    - name: Package binary
      run: |
        tar -czvf traffic-monitor.tar.gz traffic-monitor  # 将二进制文件压缩为 .tar.gz 格式

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2  # 上传压缩包
      with:
        name: traffic-monitor  # 给上传的文件起个名字
        path: traffic-monitor.tar.gz  # 上传的文件路径

